import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Grid, GridItem, Box , Heading} from '@chakra-ui/react'

import TreeMap from '../component/treemap/treemap'

import data_cusotmer from '../data/cusotmer/IC4PRO_CUSTOMER.json'
import data_exceptions  from '../data/cusotmer/IC4PRO_EXCEPTIONS.json'
import data_journal  from '../data/cusotmer/IC4PRO_JOURNAL.json'
import data_srt  from '../data/cusotmer/IC4PRO_STR.json'


import CustomerData from '../component/customer/customerData'

const style = {
  h1: {
    marginTop: '3em',
  },
  h2: {
    margin: '4em 0em 2em',
  },
  h3: {
    marginTop: '2em',
    padding: '2em 0em',
  },
  last: {
    marginBottom: '600px',
  },
}

export default function Customer() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Customer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading>Customer Account Analysis</Heading>
      <CustomerData cusotmer={data_cusotmer} exception={data_exceptions} journal={data_journal} srt={data_srt}/>
        
     

      
    </div>
  )
}
