import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Grid, GridItem, Box } from '@chakra-ui/react'

import TreeMap from '../component/treemap/treemap'

import Readdata from '../data/d3-data.json'

const style = {
  h1: {
    marginTop: '3em',
  },
  h2: {
    margin: '4em 0em 2em',
  },
  h3: {
    marginTop: '2em',
    padding: '2em 0em',
  },
  last: {
    marginBottom: '600px',
  },
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
        <TreeMap data={Readdata.callover}></TreeMap>
        
     

      
    </div>
  )
}
